package assn1;

import static org.junit.Assert.*;

import java.util.ArrayList;

import org.junit.After;
import org.junit.Test;

/**
 * Verifies the correctness of search results generated by
 * Student Searcher
 * @author drdan
 *
 */
public class StudentSearcherTest {


	@Test
	/**
	 * Verifies the correctness of search results generated by
	 * Student Searcher
	 * @author drdan
	 *
	 */
	public void testSearchResults() {
		StudentSearcher instance = new StudentSearcher();
		//this string occurs in two records
		instance.setSearchString("ald");
		ArrayList <StudentRecord> resultSet1 = instance.getSearchResults();
		assertEquals("result 1 number of records",2,resultSet1.size());
		StudentRecord result1_0 = resultSet1.get(0);
		assertEquals("First name","Christoph",result1_0.getFname());
		assertEquals("Last name","Donaldson",result1_0.getLname());
		assertEquals("Email Addr","cdonald0@uga.edu",result1_0.getEmailAddr());
		assertEquals("Image location","images/cdonald0.jpg",result1_0.getImageLocation());
		StudentRecord result1_1 = resultSet1.get(1);
		assertEquals("First name","David Clayto",result1_1.getFname());
		assertEquals("Last name","Herald",result1_1.getLname());
		assertEquals("Email Addr","jdherald@uga.edu",result1_1.getEmailAddr());
		assertEquals("Image location","images/generic.png",result1_1.getImageLocation());
		
		//this string occurs in A. Morris' email but not the name
		instance.setSearchString("atm");
		ArrayList <StudentRecord> resultSet2 = instance.getSearchResults();
		assertNotNull("Result 2",resultSet2);
		assertEquals("result 2 number of records",0,resultSet2.size());
		
		
		//this string occurs in one record, but is capitalized
		instance.setSearchString("dan");
		ArrayList <StudentRecord> resultSet3 = instance.getSearchResults();
		assertEquals("result 3 number of records",1,resultSet3.size());
		StudentRecord result3_0 = resultSet3.get(0);
		assertEquals("First name","Daniel M",result3_0.getFname());
		assertEquals("Last name","Heidenhain",result3_0.getLname());
		assertEquals("Email Addr","danielh@uga.edu",result3_0.getEmailAddr());
		
		//this string does not occur in the list of records
		instance.setSearchString("xyz");
		ArrayList <StudentRecord> resultSet5 = instance.getSearchResults();
		assertNotNull("Result 5",resultSet5);
		assertEquals("result 5 number of records",0,resultSet2.size());
		
		//upper case search String
		instance.setSearchString("ALD");
		ArrayList <StudentRecord> resultSet6 = instance.getSearchResults();
		assertNotNull("Result 6",resultSet6);
		assertEquals("result 6 number of records",2,resultSet1.size());
		StudentRecord result6_0 = resultSet6.get(0);
		assertEquals("First name","Christoph",result6_0.getFname());
		assertEquals("Last name","Donaldson",result6_0.getLname());
		assertEquals("Email Addr","cdonald0@uga.edu",result6_0.getEmailAddr());
		assertEquals("Image location","images/cdonald0.jpg",result6_0.getImageLocation());
		StudentRecord result6_1 = resultSet6.get(1);
		assertEquals("First name","David Clayto",result6_1.getFname());
		assertEquals("Last name","Herald",result6_1.getLname());
		assertEquals("Email Addr","jdherald@uga.edu",result6_1.getEmailAddr());
		assertEquals("Image location","images/generic.png",result6_1.getImageLocation());
	}

}
 